"""Applies reconcile.fleet_corrections to the live book, on a schedule.

Turned on at the account owner's instruction, 2026-09-28. What it does is
narrow on purpose: when the fleet's UNSPENT claims exceed the cash that
really exists, it reduces those claims until they fit. It never places an
order, never touches a slice, never moves a coin. It corrects a number that
had drifted away from the money behind it.

WHAT IT CANNOT DO, and every one of these is enforced in reconcile.py
rather than here, so the rules hold for any caller:

  * It never RAISES a claim. Writing an allocation up on the strength of an
    arithmetic identity would let a mis-measurement mint budget, and this
    codebase produced a wrong-but-plausible measurement twice in one evening.
  * It never reduces a branch below the coin that branch actually owns.
  * It refuses outright when a pass would remove more than half the unspent
    claims - that means the cash reading collapsed, which is a measurement
    to check, not an instruction to obey.
  * An unreadable wallet moves nothing. A gap is not a zero.

Measured before arming: unspent claims $495.02 against $515.31 of real cash,
so the first pass is a no-op. Knowing that BEFORE turning it on is the point
of having run it first.
"""
import asyncio
import logging
import os

log = logging.getLogger(__name__)

CHECK_SECONDS = int(os.getenv("GRID_RECONCILE_CHECK_SECONDS", "900"))

# DB-backed so it can be turned off without a deploy; env overrides outright.
# Matches the idle-rotation switch, for the same reason: a control that needs
# a deploy to flip is not a control you can use when something is going wrong.
RECONCILE_MODE_KEY = "grid_reconcile_mode"


def env_mode():
    raw = (os.getenv("GRID_RECONCILE_MODE") or "").strip().strip('"').strip("'").lower()
    if raw in {"arm", "armed", "on", "true", "1"}:
        return True
    if raw in {"observe", "off", "false", "0"}:
        return False
    return None


# The owner armed this on 2026-09-28, in those words. A default carries
# that instruction so it does not depend on a Railway variable nobody can
# set from here - but it is a DEFAULT, not a hardcoding: the env var and the
# DB row both override it, so it can be switched off without a deploy.
ARMED_BY_DEFAULT = True


async def armed_now(session_factory):
    """env decides outright, else the DB row, else the owner's default.

    THE THREE CASES ARE NOT THE SAME and collapsing them is the trap:

      env set          -> obey it, no question
      DB row present   -> obey it, it was set deliberately
      DB readable,
        no row         -> ARMED_BY_DEFAULT, the owner's standing instruction
      DB UNREADABLE    -> OFF, always

    The last one is why this cannot simply `return ARMED_BY_DEFAULT` on any
    exception. A worker that writes to allocations must not arm itself
    because a database read hiccupped - it cannot tell a missing switch from
    a switch it failed to read, and one of those means someone turned it off.
    """
    env = env_mode()
    if env is not None:
        return env
    try:
        from models import TradingBotState
        from sqlalchemy import select
        async with session_factory()() as db:
            row = (await db.execute(select(TradingBotState).where(
                TradingBotState.bot_name == RECONCILE_MODE_KEY))).scalar_one_or_none()
        if row is None:
            return ARMED_BY_DEFAULT
        return bool(row.base_capital and row.base_capital > 0)
    except Exception as e:
        log.warning(f"[RECONCILE] arm switch unreadable ({type(e).__name__}) - staying OFF")
        return False


# ── A CLAIM REDUCTION IS A MONEY EVENT. IT GOES WHERE HE CAN SEE IT. ──
#
# WHAT WENT WRONG. On 2026-10-09 the owner asked where $1,016.36 of his
# allocation had gone. The answer was here: this worker had written the
# claims down because they were budgeting cash that did not exist. It is
# the correct behaviour and it is why the figure could be explained at
# all. But the ONLY record it left was a Railway log line, inside a log
# printing 46,656 lines a day of unchanged state, and the owner cannot
# read Railway logs from a phone. So the books moved by a thousand
# dollars and nothing told him. His instruction, in his own words:
# "Stop that from happening."
#
# WHAT CHANGED. Nothing about the reconciliation. Not one rail, not one
# threshold, not one write. Every correction now ALSO lands on the
# activity feed the dashboard already reads, which is the same route the
# grid's own gate verdicts take to the Live Ops page - append-only,
# self-trimming, and contractually unable to raise.
#
# ONE SENTENCE, BUILT ONCE. _log_activity's own contract asks that the
# feed carry "the exact same human-readable text already going to the
# real Railway log at the call site", so the log line and the feed row
# are generated by the SAME function below. They cannot drift into saying
# different things about the same dollars, which is a defect this
# repository has shipped more than once.
#
# HONEST LIMIT, so nobody reads more permanence into this than it has:
# the feed trims to TREE_ACTIVITY_FEED_MAX_ROWS (500) and the gate writes
# to it far more often than this does, so a correction row ages out
# eventually. It is a notification, not a ledger. A durable audit row
# would need its own table and that is a bigger change than the owner
# asked for.
def reduction_line(c) -> str:
    """The one sentence describing one claim reduction.

    Pure: takes the correction dict, returns text. No clock, no database,
    no logger - so the exact wording that will reach the owner can be
    asserted in a test without standing up a worker.
    """
    before = float(c["before_usd"])
    after = float(c["new_allocated_usd"])
    return (f"[RECONCILE] {c['bot_name']} ({c['product_id']}): claim "
            f"${before:,.2f} -> ${after:,.2f} "
            f"(-${before - after:,.2f}) - it was budgeting "
            f"cash that is not there. Coin owned: "
            f"${float(c['coin_basis_usd']):,.2f}, untouched.")


async def _announce(bot_name, product_id, event_type, message, sink=None):
    """Put one line on the dashboard's activity feed. NEVER raises.

    Same contract as the feed writer it calls and the same reason for it:
    telemetry that can break the thing it is reporting on is worse than no
    telemetry. A failure here leaves the correction applied and the log
    line written; only the dashboard row is lost.

    `sink` exists for tests - the real one imports lazily because this
    module is started from main.py alongside the bot modules and a
    top-level import would close a cycle.
    """
    try:
        if sink is None:
            import crypto_family_tree_bot as tree
            sink = tree._log_activity
        await sink(bot_name, product_id, event_type, message)
    except Exception as e:
        log.warning(f"[RECONCILE] feed write failed (non-fatal, the "
                    f"correction itself is applied and logged): "
                    f"{type(e).__name__}: {e}")


async def _audit_reduction(session_factory, c, real_cash_usd, audit_sink=None):
    """Write one durable row for one claim reduction. NEVER raises.

    THE FEED IS A NOTIFICATION; THIS IS THE LEDGER. The activity feed trims
    at 500 rows and the grid's gate writes to it far more often than this
    does, so it answers "what just happened" and cannot answer "what
    happened three days ago" - which is the question that was actually
    asked. claim_reduction_audit is append-only and nothing trims it.

    Separate from _announce on purpose: a failure to notify must not cost
    the durable row, and a failure to persist must not cost the
    notification. Either one alone is still better than the log line this
    replaces.
    """
    try:
        if audit_sink is not None:
            await audit_sink(c, real_cash_usd)
            return
        from audit_models import ClaimReductionAudit
        before = float(c["before_usd"])
        after = float(c["new_allocated_usd"])
        async with session_factory()() as db:
            db.add(ClaimReductionAudit(
                bot_name=c["bot_name"],
                product_id=c["product_id"],
                previous_allocated_usd=before,
                new_allocated_usd=after,
                delta_usd=round(after - before, 2),
                coin_basis_usd=float(c.get("coin_basis_usd") or 0.0),
                real_cash_usd=(None if real_cash_usd is None
                               else float(real_cash_usd)),
                reason_code="UNBACKED_CLAIM",
                reason_detail=reduction_line(c),
                source_component="reconcile_worker",
            ))
            await db.commit()
    except Exception as e:
        log.warning(f"[RECONCILE] audit row failed (non-fatal, the "
                    f"correction itself is applied, logged and announced): "
                    f"{type(e).__name__}: {e}")


async def _branch_rows(session_factory):
    """Each branch with its own coin basis. Computed from the slices, never
    from allocated_usd - the allocation is the claim being tested, so using
    it here would make the check agree with itself."""
    from models import CryptoGridBranch, CryptoGridSlice
    from sqlalchemy import select
    async with session_factory()() as db:
        branches = (await db.execute(select(CryptoGridBranch).where(
            CryptoGridBranch.active.is_(True)))).scalars().all()
        slices = (await db.execute(select(CryptoGridSlice))).scalars().all()
    basis = {}
    for s in slices:
        if s.qty is None or s.entry_price is None:
            continue
        basis[s.bot_name] = basis.get(s.bot_name, 0.0) + float(s.qty) * float(s.entry_price)
    return [{"bot_name": b.bot_name, "product_id": b.product_id,
             "allocated_usd": b.allocated_usd,
             "coin_basis_usd": round(basis.get(b.bot_name, 0.0), 2)}
            for b in branches]


async def run_once(session_factory, real_cash_usd, dry_run=True, sink=None,
                   audit_sink=None):
    """One pass. Returns the report plus what was applied.

    `sink` is the activity-feed writer and `audit_sink` the durable-row
    writer, both injectable so a test can read the exact rows the owner
    would see - one on his dashboard, one in the ledger - without a
    database.
    """
    import reconcile as rec
    rows = await _branch_rows(session_factory)
    corrections, report = rec.fleet_corrections(rows, real_cash_usd)
    report["dry_run"] = bool(dry_run)
    report["corrections"] = corrections
    if dry_run or not corrections:
        report["applied"] = 0
        return report

    from models import CryptoGridBranch
    from sqlalchemy import select
    applied = 0
    announced = []
    async with session_factory()() as db:
        for c in corrections:
            row = (await db.execute(select(CryptoGridBranch).where(
                CryptoGridBranch.bot_name == c["bot_name"]))).scalar_one_or_none()
            if row is None:
                continue
            # RE-CHECKED against the live row, not the planned one. A branch
            # whose allocation moved between the plan and now must not be
            # written from a stale figure, and one that is already at or
            # below the target is left alone - the write only ever lowers.
            if row.allocated_usd is None or float(row.allocated_usd) <= c["new_allocated_usd"]:
                continue
            before = float(row.allocated_usd)
            row.allocated_usd = c["new_allocated_usd"]
            applied += 1
            # The LIVE before-figure, not the planned one, so the sentence
            # the owner reads is the money that actually moved.
            c["before_usd"] = before
            line = reduction_line(c)
            log.warning(line)
            announced.append(c)
        await db.commit()
    # Announced only after the commit. A feed row for a correction that
    # rolled back would be a lie about his money, and the ordering is the
    # only thing that prevents it.
    audited = 0
    for c in announced:
        await _announce(c["bot_name"], c["product_id"], "CLAIM_REDUCED",
                        reduction_line(c), sink=sink)
        await _audit_reduction(session_factory, c, real_cash_usd,
                               audit_sink=audit_sink)
        audited += 1
    report["applied"] = applied
    report["announced"] = len(announced)
    report["audited"] = audited
    return report


async def loop(session_factory, cash_reader):
    """Forever. cash_reader() -> real spendable+held USD, or None."""
    log.warning(f"[RECONCILE] claim-reconciliation loop started "
                f"(every {CHECK_SECONDS}s, writes only when armed)")
    while True:
        try:
            armed = await armed_now(session_factory)
            cash = await cash_reader()
            report = await run_once(session_factory, cash, dry_run=not armed)
            if report.get("status") in ("REFUSED", "UNKNOWN"):
                # The protection DECLINING to act is a state he should see.
                # A refused pass means the cash reading collapsed or the
                # wallet could not be read, and silence there looks exactly
                # like a healthy quiet fleet.
                _msg = f"[RECONCILE] {report['status']}: {report.get('detail')}"
                log.warning(_msg)
                await _announce("grid", "fleet",
                                f"RECONCILE_{report['status']}", _msg)
            elif report.get("applied"):
                log.warning(f"[RECONCILE] applied {report['applied']} correction(s): "
                            f"{report.get('detail')}")
            elif report.get("corrections") and not armed:
                log.warning(f"[RECONCILE] OBSERVING - would correct "
                            f"{len(report['corrections'])} claim(s): {report.get('detail')}")
        except Exception as e:
            log.warning(f"[RECONCILE] pass failed ({type(e).__name__}: {e}) - "
                        f"nothing written, retrying next cycle")
        await asyncio.sleep(CHECK_SECONDS)
